image: python:3.10

stages:
  - lint
  - test

pylint:
  stage: lint
  script:
    - pip install pylint
    - python3 -m pylint .

pytest:
  stage: test
  script:
    - pip install pytest
    - python3 -m pytest .